

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'; 
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'; 
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'; 

export const LOAD_MY_INFORMATION_REQUEST = 'LOAD_MY_INFORMATION_REQUEST';
export const LOAD_MY_INFORMATION_SUCCESS = 'LOAD_MY_INFORMATION_SUCCESS';
export const LOAD_MY_INFORMATION_FAILURE = 'LOAD_MY_INFORMATION_FAILURE';

export const LOAD_USER_INFORMATION_REQUEST = 'LOAD_USER_INFORMATION_REQUEST';
export const LOAD_USER_INFORMATION_SUCCESS = 'LOAD_USER_INFORMATION_SUCCESS';
export const LOAD_USER_INFORMATION_FAILURE = 'LOAD_USER_INFORMATION_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const CHANGE_PROFILE_PICTURE_REQUEST = 'CHANGE_PROFILE_PICTURE_REQUEST';
export const CHANGE_PROFILE_PICTURE_SUCCESS = 'CHANGE_PROFILE_PICTURE_SUCCESS';
export const CHANGE_PROFILE_PICTURE_FAILURE = 'CHANGE_PROFILE_PICTURE_FAILURE';

export const CHANGE_SUBNICKNAME_REQUEST = 'CHANGE_SUBNICKNAME_REQUEST';
export const CHANGE_SUBNICKNAME_SUCCESS = 'CHANGE_SUBNICKNAME_SUCCESS';
export const CHANGE_SUBNICKNAME_FAILURE = 'CHANGE_SUBNICKNAME_FAILURE';

export const CHANGE_BIO_REQUSET = 'CHANGE_BIO_REQUSET';
export const CHANGE_BIO_SUCCESS = 'CHANGE_BIO_SUCCESS';
export const CHANGE_BIO_FAILURE = 'CHANGE_BIO_FAILURE';

export const CHANGE_BACKGROUND_REQUEST = 'CHANGE_BACKGROUND_REQUEST';
export const CHANGE_BACKGROUND_SUCCESS = 'CHANGE_BACKGROUND_SUCCESS';
export const CHANGE_BACKGROUND_FAILURE = 'CHANGE_BACKGROUND_FAILURE';

export const SIGN_UP_CHECKED = 'SIGN_UP_CHECKED';